### ISSUE TITLE
IONOS  deployment Github workflow failing

### ISSUE THREAD

**Issue by raythompsonwebdev** [raythompsonwebdev/raythompsonwebsite-fc#9]
Deployment not working. 
getting error message -  Error : .github#L1 every step must define a `uses` or `run` key
Checked deploy-now.yml file. all steps as far as I can see a uses key has been defined.  no run key used. Can't see the issue

```
name: Deploy Now

on:
  - push
  - workflow_dispatch

jobs:
  deploy-now:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: ${{ secrets.IONOS_PROJECT_ID }}
          service-host: api-eu.ionos.space
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Custom
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
      - name: Deploy build
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          bootstrap-deploy: ${{ steps.project.outputs.bootstrap-deploy }}
          branch-id: ${{ steps.project.outputs.branch-id }}
          dist-folder: /
          project: ${{ secrets.IONOS_PROJECT_ID }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          service-host: api-eu.ionos.space
          storage-quota: ${{ steps.project.outputs.storage-quota }}
```
 
I have contacted IONOS. 
advised ticket was sent to hosting team.
awaiting reply
